### ISSUE TITLE
getTotalSpace implementation is wrong [Android]

### ISSUE THREAD

**Issue by bonnyfone** [oodavid/storage_space#1]
The **getTotalSpace** implementation for **Android** seems wrong:

https://github.com/oodavid/storage_space/blob/869cf11b576e1dc5ed5d806822795bb602940c08/android/src/main/kotlin/com/oodavid/storage_space/StorageSpacePlugin.kt#L54

This:
```
    else if(call.method == "getTotalSpace") {
      val stat = StatFs(Environment.getDataDirectory().getPath())
      val bytesAvailable = stat.getFreeBytes()
      val bytesOccupied = stat.getTotalBytes()
      result.success(bytesOccupied+bytesAvailable)
    }
    
```

Should be:
```
    else if(call.method == "getTotalSpace"){
      val stat = StatFs(Environment.getDataDirectory().getPath())
      val bytesTotal = stat.getTotalBytes()
      result.success(bytesTotal)
    }
```

Since `StorageStatsManager.getTotalBytes` already returns the total space:
https://developer.android.com/reference/android/app/usage/StorageStatsManager#getTotalBytes(java.util.UUID)

**Comment by oodavid** [comment]
@bonnyfone - thanks for this, I've merged your PR and updated the package.

This is now available on [storage_space 1.0.1](https://pub.dev/packages/storage_space)
